### ISSUE TITLE
IndexError: 

### ISSUE THREAD

**Issue by cqgg-163** [SCUT-BIP-Lab/PointDC#4]
Hi author, first, great work.
I encountered an IndexError: "boolean index did not match indexed array along dimension 0; dimension is 422130 but corresponding boolean dimension is 422242."
![ERROR2](https://github.com/user-attachments/assets/4b107383-9647-488e-8d54-7bd57d942cb4)
![R2](https://github.com/user-attachments/assets/ae79520f-fcfe-42f4-94cd-17844d4ecc4d)
Aside from the necessary data preparation.I made the following modifications only in the code file S3DIS.py.
![error](https://github.com/user-attachments/assets/d528e2da-865c-4154-b361-6633dd757767)

**Comment by HalvesChen** [comment]
Hi, It looks like a data mismatch. `data = region_file = self.args.sp_path + 'initial_superpoints_rebuild/' + self.name[index] + '_rebuild_superpoint.npy'` The line of code reads the data. To avoid randomness issues, you need to directly download it.

**Comment by cqgg-163** [comment]
But I did  directly download the data before.
![DATA](https://github.com/user-attachments/assets/a4445785-1462-4f21-a2d8-ad223bb4528d)

**Comment by HalvesChen** [comment]
Check out the shape of `region` and `clip_inds` and `coords`.

**Comment by HalvesChen** [comment]
Come to think of it, did you download the unaligned version of the S3DIS dataset? You can try it

**Comment by cqgg-163** [comment]
Thank you very much for your help. But I encountered the same issue on another device, following the README. the shape of region and clip_inds and coords :
![shape](https://github.com/user-attachments/assets/364a52dd-bd8a-47d7-a883-ef55b3ddf8dd)

**Comment by HalvesChen** [comment]
Which version of minkowski are you using？As I changed my work environment, I can't debug quickly at present, and I'm downloading relevant data.

**Comment by cqgg-163** [comment]
The latest version, 0.5.4

**Comment by HalvesChen** [comment]
By the way, What version of S3DIS are you using?

**Comment by cqgg-163** [comment]
2023.04.05
![3DDATA](https://github.com/user-attachments/assets/15d89c53-d373-4d20-b14e-22b5c0028f8f)

**Comment by HalvesChen** [comment]
You can try the unaligned version

**Comment by HalvesChen** [comment]
Hello, any other questions? @cqgg-163

**Comment by cqgg-163** [comment]
Thank you very much for your help. I am currently running initialSP_prepare_S3DIS.py with no further issues.
